language: "node_js"
node_js:
  - "10.15.0"
  deploy:
    provider: heroku
    api_key:
      secure
services:
  - postgresql
before_script:
  - psql -c 'create database ireporter;' -U postgres
script:
  - npm run migrate
  - npm run test
after_success: npm run coverage