CREATE TABLE IF NOT EXISTS users(
    id UUID PRIMARY KEY,
    firstname VARCHAR(128) NOT NULL,
    lastname VARCHAR(128) NOT NULL,
    othernames VARCHAR(128),
    phone_number INTEGER,
    email VARCHAR(128) UNIQUE NOT NULL,
    username VARCHAR(128) UNIQUE NOT NULL,
    password VARCHAR(128) NOT NULL,
    registered TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_admin BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS incidents(
    id UUID PRIMARY KEY,
    created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID NOT NULL,
    type VARCHAR(128) NOT NULL,
    location VARCHAR(128) NOT NULL,
    status VARCHAR(128) DEFAULT 'draft',
    Images VARCHAR(128),
    Videos VARCHAR(128),
    comment VARCHAR(128) NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE CASCADE
);